appId=3a62a814-fc91-43b5-9023-5b07f06ca6fd
activityColection=true
maxActivityDepth=30
maxCollectTime=1800000
maxNoOpTime=16000
cpuUsageCollection=true
cpuDuration=5
cpuTimes=20
memoryUsageCollection=true
memoryDuration=5
memoryTimes=20
appBootCollection=true
appRegistCollection=true
networkAccess=true
databaseCollection=true
way=\u672A\u77E5
SLEEP_TIME=3000
crashCollection=true
customEventCollection=true
