appId=05434b1d-3379-4b86-81ca-62285bf8e34e
activityColection=true
maxActivityDepth=30
maxCollectTime=1800000
maxNoOpTime=16000
cpuUsageCollection=true
cpuDuration=5
cpuTimes=20
memoryUsageCollection=true
memoryDuration=5
memoryTimes=20
appBootCollection=true
appRegistCollection=true
networkAccess=true
databaseCollection=true
way=\u672A\u77E5
SLEEP_TIME=3000
crashCollection=false
customEventCollection=true
